const { chromium } = require(process.env.PLAYWRIGHT_MODULE || 'playwright');
const fs = require('fs/promises'); const path = require('path'); const assert = require('assert/strict');
(async () => {
 const browser = await chromium.launch({ executablePath: 'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe', headless: true });
 const page = await browser.newPage({ viewport: {width:1280,height:900} });
 page.setDefaultTimeout(15000); const errors=[]; page.on('pageerror', error => errors.push(error.message));
 try {
  await page.route('**/*', async route => {
   const url = new URL(route.request().url()); if (url.hostname !== 'qa.local') return route.abort();
   const name=decodeURIComponent(url.pathname).replace(/^\//,'') || 'index.html';
   if (name === 'api/preview_model_request') {
    const script = 'import json,sys; from claude_chat.request_params import preview_generation_params,validate_request_params; d=json.loads(sys.argv[1]); p=preview_generation_params(d["platform"],d["model"],{"model_configs":{d["model"]:d.get("model_config",{})}}); validate_request_params(p,d["platform"]); print(json.dumps({"params":p},ensure_ascii=False))';
    const {stdout} = await require('util').promisify(require('child_process').execFile)('python',['-c',script,route.request().postData()],{env:{...process.env,PYTHONIOENCODING:'utf-8'}});
    return route.fulfill({json:JSON.parse(stdout)});
   }
   if (name.startsWith('api/')) return route.fulfill({json:{}});
   let body = await fs.readFile(path.join(process.cwd(),'claude_chat/ui',name));
   if(name==='index.html') body=Buffer.from(body.toString().replace('<script src="main.js"></script>',''));
   const type={'.html':'text/html','.js':'text/javascript','.css':'text/css','.woff2':'font/woff2'}[path.extname(name)] || 'application/octet-stream';
   await route.fulfill({body,contentType:type});
  });
  await page.goto('http://qa.local/');
  await page.evaluate(() => {
   window.securityToken = ""; window.savedConfig = {active_platform:'claude',enable_web_search:true,model:'model-one',model_configs:{},system_prompts:[{id:'writer',name:'写作助手',content:'Write'}],selected_system_prompt_id:'writer'};
   config=structuredClone(window.savedConfig);
   availableModels=[{id:'model-one',display_name:'Test Model One',thinking_supported:true,effort_levels:['low','high']},{id:'model-two',display_name:'Test Model Two'}];
   apiBridge.get_config=async()=>structuredClone(window.savedConfig);
   apiBridge.save_config=async(next)=>{Object.assign(window.savedConfig,structuredClone(next)); return true;};
   apiBridge.list_custom_providers=async()=>[]; apiBridge.check_parsers=async()=>({});
   apiBridge.check_code_sandbox_environment=async()=>({ready:false}); apiBridge.fetch_models=async()=>availableModels;
   updateModelList(availableModels,'model-one',true); renderSystemPromptSelect(); SelectPicker.refreshAll();
  });
  await page.locator('#platform-select-picker-trigger').click();
  await page.locator('.unified-picker-panel:not(.hidden) input').fill('DeepSeek');
  assert.equal(await page.locator('.unified-picker-panel:not(.hidden) .model-picker-option').count(),1);
  await page.keyboard.press('Escape');
  await page.locator('#system-prompt-select-picker-trigger').click();
  await page.locator('.unified-picker-panel:not(.hidden) .model-picker-option').filter({hasText:'无系统提示词'}).click();
  assert.equal(await page.locator('#system-prompt-select').inputValue(),'');
  assert.match(await page.locator('#system-prompt-select-picker-trigger').innerText(),/无系统提示词/);
  await page.evaluate(() => {const group=document.createElement('optgroup'); group.label='自定义'; const o=document.createElement('option'); o.value='custom:qa'; o.textContent='QA Provider'; group.append(o); document.getElementById('platform-select').append(group);});
  await page.locator('#platform-select-picker-trigger').click();
  await page.locator('.unified-picker-panel:not(.hidden) input').fill('QA');
  assert.equal(await page.locator('.unified-picker-panel:not(.hidden) .model-picker-option').count(),1);
  await page.keyboard.press('Escape');
  await page.locator('#settings-btn').click();
  await page.waitForFunction(()=>!document.getElementById('model-request-json').disabled);
  assert.equal(await page.locator('#model-request-json-error').innerText(),'');
  const nativeCount=await page.locator('#settings-modal select').count();
  assert.equal(await page.locator('#settings-modal select.unified-select-native').count(),nativeCount);
  await page.locator('#claude-search-engine-select-picker-trigger').click();
  const popup=page.locator('.unified-picker-panel:not(.hidden)'); assert.equal(await popup.count(),1);
  assert.equal(await popup.evaluate(el=>el.closest('.modal-overlay').id),'settings-modal');
  await page.keyboard.press('Escape'); assert(await page.locator('#settings-modal').isVisible());
  await page.locator('[data-settings-nav="model"]').click();
  await page.locator('#add-custom-param-btn').click();
  const row=page.locator('.custom-param-row').first(); await row.locator('input').fill('top_p');
  await row.locator('.settings-picker-trigger').click();
  await page.locator('.unified-picker-panel:not(.hidden) .model-picker-option').filter({hasText:'数字'}).click();
  await row.locator('textarea').fill('0.85'); await page.locator('#save-settings-btn').click();
  await page.waitForFunction(()=>document.getElementById('settings-modal').classList.contains('hidden'),null,{timeout:8000});
  assert.equal(await page.evaluate(()=>window.savedConfig.model_configs['model-one'].custom_params.top_p),0.85);
  await page.locator('#settings-btn').click();
  await page.waitForFunction(()=>!document.getElementById('model-request-json').disabled);
  assert.equal(await page.locator('#model-request-json-error').innerText(),'');
  assert.equal(await page.locator('.custom-param-row textarea').inputValue(),'0.85');
  await page.locator('[data-settings-nav="model"]').click();
  await page.locator('.custom-param-row textarea').fill('not a number'); await page.locator('#save-settings-btn').click();
  assert.match(await page.locator('#custom-params-error').innerText(),/数字/); assert(await page.locator('#settings-modal').isVisible());
  await page.locator('.custom-param-row textarea').fill('0.85');
  await page.evaluate(() => { const el=document.getElementById("custom-params-list"); const content=document.querySelector(".settings-content"); content.scrollTop += el.getBoundingClientRect().top - content.getBoundingClientRect().top - 170; });

  await page.setViewportSize({width:390,height:844});
  await page.locator('.custom-param-row .settings-picker-trigger').click();
  const box=await page.locator('.unified-picker-panel:not(.hidden)').boundingBox();
  assert(box.x>=0 && box.x+box.width<=391 && box.y>=0 && box.y+box.height<=845,JSON.stringify(box));

  await page.keyboard.press('Escape'); await page.locator('.custom-param-row .remove-param').click();
  await page.locator('#save-settings-btn').click();
  await page.waitForFunction(()=>document.getElementById('settings-modal').classList.contains('hidden'),null,{timeout:8000});
  assert.deepEqual(await page.evaluate(()=>window.savedConfig.model_configs['model-one'].custom_params),{});

  await page.setViewportSize({width:1280,height:900});
  await page.locator('#settings-btn').click();
  await page.waitForFunction(()=>!document.getElementById('model-request-json').disabled);
  const editor=page.locator('#model-request-json');
  const json={max_tokens:4096,temperature:0.333,thinking:{type:'enabled',budget_tokens:512},output_config:{format:{type:'json_schema',schema:{type:'object'}}},top_p:0.6,metadata:{user_id:'test'}};
  await editor.fill(JSON.stringify(json));
  if (process.env.UI_QA_SCREENSHOTS) {
   await fs.mkdir(process.env.UI_QA_SCREENSHOTS,{recursive:true});
   await page.locator('#format-model-json-btn').click();
   await editor.scrollIntoViewIfNeeded();
   await page.screenshot({path:path.join(process.env.UI_QA_SCREENSHOTS,'model-json-desktop.png')});
   await page.setViewportSize({width:390,height:844});
   await editor.scrollIntoViewIfNeeded();
   await page.screenshot({path:path.join(process.env.UI_QA_SCREENSHOTS,'model-json-mobile.png')});
   await page.setViewportSize({width:1280,height:900});
  }
  assert.equal(await page.locator('#model-temp-input').inputValue(),'0.333');
  assert.equal(await page.locator('#model-max-tokens-input').inputValue(),'4096');
  assert.equal(await page.locator('#model-thinking-budget-input').inputValue(),'512');
  assert(await page.locator('#model-thinking-enabled-input').isChecked());
  assert(await page.locator('input[name="model-thinking-type"][value="enabled"]').isChecked());
  assert.equal(await page.locator('.custom-param-row').count(),2);
  await page.locator('input[name="model-thinking-type"][value="adaptive"]').check();
  assert.deepEqual(JSON.parse(await editor.inputValue()).output_config.format,json.output_config.format);
  assert(!('budget_tokens' in JSON.parse(await editor.inputValue()).thinking));
  await page.locator('#model-temp-input').fill('0.421');
  assert.equal(JSON.parse(await editor.inputValue()).temperature,0.421);
  await page.locator('#model-temp-enabled').uncheck();
  assert(!('temperature' in JSON.parse(await editor.inputValue())));
  assert(await page.locator('#model-temp-input').isDisabled());
  const lastValid=JSON.parse(await editor.inputValue());
  await editor.fill('{"temperature":');
  await page.locator('#save-settings-btn').click();
  assert(await page.locator('#settings-modal').isVisible());
  assert.match(await page.locator('#model-request-json-error').innerText(),/JSON/);
  await page.locator('#restore-model-json-btn').click();
  assert.deepEqual(JSON.parse(await editor.inputValue()),lastValid);
  await page.locator('#add-custom-param-btn').click();
  const countBefore=await page.locator('.custom-param-row').count();
  await page.locator('#save-settings-btn').click();
  assert.equal(await page.locator('.custom-param-row').count(),countBefore);
  assert(await page.locator('#settings-modal').isVisible());
  await page.locator('.custom-param-row .remove-param').last().click();
  delete json.thinking; delete json.top_p; delete json.temperature;
  await editor.fill(JSON.stringify(json));
  assert(!(await page.locator('#model-thinking-enabled-input').isChecked()));
  assert.equal(await page.locator('.custom-param-row').count(),1);
  await page.locator('#save-settings-btn').click();
  await page.waitForFunction(()=>document.getElementById('settings-modal').classList.contains('hidden'));
  assert.deepEqual(await page.evaluate(()=>window.savedConfig.model_configs['model-one'].request_params),json);
  await page.locator('#settings-btn').click();
  await page.waitForFunction(()=>!document.getElementById('model-request-json').disabled);
  assert.deepEqual(JSON.parse(await editor.inputValue()),json);
  assert(await page.locator('#model-temp-input').isDisabled());
  // Different provider schemas are recognized without model-registry capability gating.
  await page.evaluate(async()=>{await ModelConfigEditor.load('model-one','deepseek',{request_params:{max_tokens:2048,temperature:0.123,reasoning_effort:'medium'}});});
  assert.equal(await page.locator('#model-thinking-level-select').inputValue(),'medium');
  assert(await page.locator('#model-thinking-enabled-input').isChecked());
  await page.locator('#model-thinking-enabled-input').uncheck();
  assert(!('reasoning_effort' in JSON.parse(await editor.inputValue())));
  await page.evaluate(async()=>{await ModelConfigEditor.load('model-one','gemini',{request_params:{max_output_tokens:2048,thinking_config:{thinking_budget:512,include_thoughts:true},top_p:0.8}});});
  assert.equal(await page.locator('#model-max-tokens-input').inputValue(),'2048');
  assert.equal(await page.locator('#model-thinking-budget-input').inputValue(),'512');
  await page.locator('#model-thinking-budget-input').fill('1024');
  assert.deepEqual(JSON.parse(await editor.inputValue()).thinking_config,{thinking_budget:1024,include_thoughts:true});
  await page.evaluate(async()=>{ModelConfigEditor.reset(); const first=ModelConfigEditor.load('model-one','claude',{}); const second=ModelConfigEditor.load('model-two','deepseek',{}); await Promise.all([first,second]);});
  assert(await page.locator('#add-custom-param-btn').isEnabled());
  // A validation response for an old draft must not overwrite more recent edits.
  await page.evaluate(()=>{window.realPreview=apiBridge.preview_model_request; apiBridge.preview_model_request=data=>new Promise(resolve=>{window.resolvePreview=()=>resolve({params:data.model_config.request_params});}); window.pendingDraft=ModelConfigEditor.prepareSave();});
  await page.waitForFunction(()=>!!window.resolvePreview);
  await editor.fill('{"temperature":0.456}');
  assert.equal(await page.evaluate(async()=>{window.resolvePreview(); const result=await window.pendingDraft; apiBridge.preview_model_request=window.realPreview; return result;}),null);
  assert.equal(JSON.parse(await editor.inputValue()).temperature,0.456);
  assert.deepEqual(errors,[]);
  console.log('Browser QA passed: dropdown regressions, JSON/form synchronization, precision, nested fields, deletion, save/reopen, invalid drafts, provider schemas and stale-response protection.');
 } catch(e) { console.log(await page.locator("#model-request-json-error").innerText(),await page.locator("#custom-params-error").innerText(),await page.locator("#model-request-json").inputValue()); console.log(errors); throw e; } finally { await browser.close(); }
})().catch(e=>{console.error(e);process.exitCode=1;});
