const { chromium } = require(process.env.PLAYWRIGHT_MODULE || 'playwright');
const fs = require('fs/promises'); const path = require('path'); const assert = require('assert/strict');
(async () => {
 const browser = await chromium.launch({ executablePath: 'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe', headless: true });
 const page = await browser.newPage({ viewport: {width:1280,height:900} });
 page.setDefaultTimeout(15000); const errors=[]; page.on('pageerror', error => errors.push(error.message));
 try {
  await page.route('**/*', async route => {
   const url = new URL(route.request().url()); if (url.hostname !== 'qa.local') return route.abort();
   const name=decodeURIComponent(url.pathname).replace(/^\//,'') || 'index.html';
   if (name === 'api/preview_model_request') {
    const script = 'import json,sys; from claude_chat.request_params import preview_generation_params,request_protocol; d=json.loads(sys.argv[1]); c={"deepseek_use_responses":d.get("deepseek_use_responses",False),"model_configs":{d["model"]:d.get("model_config",{})},"custom_providers":[{"id":"responses-qa","provider_adapter":"responses"}]}; p=preview_generation_params(d["platform"],d["model"],c); print(json.dumps({"params":p,"request_protocol":request_protocol(d["platform"],c)},ensure_ascii=False))';
    const {stdout} = await require('util').promisify(require('child_process').execFile)(process.env.PYTHON_EXECUTABLE || 'python',['-c',script,route.request().postData()],{env:{...process.env,PYTHONIOENCODING:'utf-8'}});
    return route.fulfill({json:JSON.parse(stdout)});
   }
   if (name.startsWith('api/')) return route.fulfill({json:{}});
   let body = await fs.readFile(path.join(process.cwd(),'claude_chat/ui',name));
   if(name==='index.html') body=Buffer.from(body.toString().replace('<script src="main.js"></script>',''));
   const type={'.html':'text/html','.js':'text/javascript','.css':'text/css','.woff2':'font/woff2'}[path.extname(name)] || 'application/octet-stream';
   await route.fulfill({body,contentType:type});
  });
  await page.goto('http://qa.local/');
  await page.evaluate(() => {
   window.securityToken = ""; window.savedConfig = {active_platform:'claude',enable_web_search:true,model:'model-one',model_configs:{},system_prompts:[{id:'writer',name:'写作助手',content:'Write'}],selected_system_prompt_id:'writer'};
   config=structuredClone(window.savedConfig);
   availableModels=[{id:'model-one',display_name:'Test Model One',thinking_supported:true,effort_levels:['low','high']},{id:'model-two',display_name:'Test Model Two'}];
   apiBridge.get_config=async()=>structuredClone(window.savedConfig);
   apiBridge.save_config=async(next)=>{Object.assign(window.savedConfig,structuredClone(next)); return true;};
   apiBridge.list_custom_providers=async()=>[]; apiBridge.check_parsers=async()=>({});
   apiBridge.check_code_sandbox_environment=async()=>({ready:false}); apiBridge.fetch_models=async()=>availableModels;
   updateModelList(availableModels,'model-one',true); renderSystemPromptSelect(); SelectPicker.refreshAll();
  });
  await page.locator('#platform-select-picker-trigger').click();
  await page.locator('.unified-picker-panel:not(.hidden) input').fill('DeepSeek');
  assert.equal(await page.locator('.unified-picker-panel:not(.hidden) .model-picker-option').count(),1);
  await page.keyboard.press('Escape');
  await page.locator('#system-prompt-select-picker-trigger').click();
  await page.locator('.unified-picker-panel:not(.hidden) .model-picker-option').filter({hasText:'无系统提示词'}).click();
  assert.equal(await page.locator('#system-prompt-select').inputValue(),'');
  assert.match(await page.locator('#system-prompt-select-picker-trigger').innerText(),/无系统提示词/);
  await page.evaluate(() => {const group=document.createElement('optgroup'); group.label='自定义'; const o=document.createElement('option'); o.value='custom:qa'; o.textContent='QA Provider'; group.append(o); document.getElementById('platform-select').append(group);});
  await page.locator('#platform-select-picker-trigger').click();
  await page.locator('.unified-picker-panel:not(.hidden) input').fill('QA');
  assert.equal(await page.locator('.unified-picker-panel:not(.hidden) .model-picker-option').count(),1);
  await page.keyboard.press('Escape');
  await page.locator('#settings-btn').click();
  await page.waitForFunction(()=>!document.getElementById('model-request-json').disabled);
  await page.locator('[data-settings-nav="providers"]').click();
  assert.equal(await page.locator('#model-request-json-error').innerText(),'');
  const nativeCount=await page.locator('#settings-modal select').count();
  assert.equal(await page.locator('#settings-modal select.unified-select-native').count(),nativeCount);
  await page.locator('#claude-search-engine-select-picker-trigger').click();
  const popup=page.locator('.unified-picker-panel:not(.hidden)'); assert.equal(await popup.count(),1);
  assert.equal(await popup.evaluate(el=>el.closest('.modal-overlay').id),'settings-modal');
  await page.keyboard.press('Escape'); assert(await page.locator('#settings-modal').isVisible());
  await page.locator('[data-settings-nav="model"]').click();
  await page.locator('#add-custom-param-btn').click();
  const row=page.locator('.custom-param-row').first(); await row.locator('input').fill('top_p');
  await row.locator('.settings-picker-trigger').click();
  await page.locator('.unified-picker-panel:not(.hidden) .model-picker-option').filter({hasText:'数字'}).click();
  await row.locator('textarea').fill('0.85'); await page.locator('#save-settings-btn').click();
  await page.waitForFunction(()=>document.getElementById('settings-modal').classList.contains('hidden'),null,{timeout:8000});
  assert.equal(await page.evaluate(()=>window.savedConfig.model_configs['model-one'].custom_params.top_p),0.85);
  await page.locator('#settings-btn').click();
  await page.waitForFunction(()=>!document.getElementById('model-request-json').disabled);
  await page.locator('[data-settings-nav="model"]').click();
  assert.equal(await page.locator('#model-request-json-error').innerText(),'');
  assert.equal(await page.locator('.custom-param-row textarea').inputValue(),'0.85');
  await page.locator('[data-settings-nav="model"]').click();
  await page.locator('.custom-param-row textarea').fill('not a number'); await page.locator('#save-settings-btn').click();
  assert.match(await page.locator('#custom-params-error').innerText(),/数字/); assert(await page.locator('#settings-modal').isVisible());
  await page.locator('.custom-param-row textarea').fill('0.85');
  await page.evaluate(() => { const el=document.getElementById("custom-params-list"); const content=document.querySelector(".settings-content"); content.scrollTop += el.getBoundingClientRect().top - content.getBoundingClientRect().top - 170; });

  await page.setViewportSize({width:390,height:844});
  await page.locator('.custom-param-row .settings-picker-trigger').click();
  const box=await page.locator('.unified-picker-panel:not(.hidden)').boundingBox();
  assert(box.x>=0 && box.x+box.width<=391 && box.y>=0 && box.y+box.height<=845,JSON.stringify(box));

  await page.keyboard.press('Escape'); await page.locator('.custom-param-row .remove-param').click();
  await page.locator('#save-settings-btn').click();
  await page.waitForFunction(()=>document.getElementById('settings-modal').classList.contains('hidden'),null,{timeout:8000});
  assert.deepEqual(await page.evaluate(()=>window.savedConfig.model_configs['model-one'].custom_params),{});

  await page.setViewportSize({width:1280,height:900});
  await page.locator('#settings-btn').click();
  await page.waitForFunction(()=>!document.getElementById('model-request-json').disabled);
  await page.locator('[data-settings-nav="model"]').click();
  const editor=page.locator('#model-request-json');
  const json={max_tokens:4096,temperature:0.333,thinking:{type:'enabled',budget_tokens:512},output_config:{format:{type:'json_schema',schema:{type:'object'}}},top_p:0.6,metadata:{user_id:'test'}};
  await editor.fill(JSON.stringify(json));
  if (process.env.UI_QA_SCREENSHOTS) {
   await fs.mkdir(process.env.UI_QA_SCREENSHOTS,{recursive:true});
   await page.locator('#format-model-json-btn').click();
   await editor.scrollIntoViewIfNeeded();
   await page.screenshot({path:path.join(process.env.UI_QA_SCREENSHOTS,'model-json-desktop.png')});
   await page.setViewportSize({width:390,height:844});
   await editor.scrollIntoViewIfNeeded();
   await page.screenshot({path:path.join(process.env.UI_QA_SCREENSHOTS,'model-json-mobile.png')});
   await page.setViewportSize({width:1280,height:900});
  }
  assert.equal(await page.locator('#model-temp-input').inputValue(),'0.333');
  assert.equal(await page.locator('#model-max-tokens-input').inputValue(),'4096');
  assert.equal(await page.locator('#model-thinking-budget-input').inputValue(),'512');
  assert(await page.locator('#model-thinking-enabled-input').isChecked());
  assert(await page.locator('input[name="model-thinking-type"][value="enabled"]').isChecked());
  assert.equal(await page.locator('.custom-param-row').count(),2);
  await page.locator('input[name="model-thinking-type"][value="adaptive"]').check();
  assert.deepEqual(JSON.parse(await editor.inputValue()).output_config.format,json.output_config.format);
  assert(!('budget_tokens' in JSON.parse(await editor.inputValue()).thinking));
  await page.locator('#model-temp-input').fill('0.421');
  assert.equal(JSON.parse(await editor.inputValue()).temperature,0.421);
  await page.locator('#model-temp-enabled').uncheck();
  assert(!('temperature' in JSON.parse(await editor.inputValue())));
  assert(await page.locator('#model-temp-input').isDisabled());
  const lastValid=JSON.parse(await editor.inputValue());
  await editor.fill('{"temperature":');
  await page.locator('#save-settings-btn').click();
  assert(await page.locator('#settings-modal').isVisible());
  assert.match(await page.locator('#model-request-json-error').innerText(),/JSON/);
  await page.locator('#restore-model-json-btn').click();
  assert.deepEqual(JSON.parse(await editor.inputValue()),lastValid);
  await page.locator('#add-custom-param-btn').click();
  const countBefore=await page.locator('.custom-param-row').count();
  await page.locator('#save-settings-btn').click();
  assert.equal(await page.locator('.custom-param-row').count(),countBefore);
  assert(await page.locator('#settings-modal').isVisible());
  await page.locator('.custom-param-row .remove-param').last().click();
  delete json.thinking; delete json.top_p; delete json.temperature;
  await editor.fill(JSON.stringify(json));
  assert(!(await page.locator('#model-thinking-enabled-input').isChecked()));
  assert.equal(await page.locator('.custom-param-row').count(),1);
  await page.locator('#save-settings-btn').click();
  await page.waitForFunction(()=>document.getElementById('settings-modal').classList.contains('hidden'));
  assert.deepEqual(await page.evaluate(()=>window.savedConfig.model_configs['model-one'].request_params),json);
  await page.locator('#settings-btn').click();
  await page.waitForFunction(()=>!document.getElementById('model-request-json').disabled);
  await page.locator('[data-settings-nav="model"]').click();
  assert.deepEqual(JSON.parse(await editor.inputValue()),json);
  assert(await page.locator('#model-temp-input').isDisabled());
  // Different provider schemas are recognized without model-registry capability gating.
  await page.evaluate(async()=>{await ModelConfigEditor.load('model-one','deepseek',{request_params:{max_tokens:2048,temperature:0.123,reasoning_effort:'medium'}});});
  assert.equal(await page.locator('#model-thinking-level-select').inputValue(),'medium');
  assert(await page.locator('#model-thinking-enabled-input').isChecked());
  await page.locator('#model-thinking-enabled-input').uncheck();
  assert(!('reasoning_effort' in JSON.parse(await editor.inputValue())));
  await page.evaluate(async()=>{await ModelConfigEditor.load('model-one','gemini',{request_params:{max_output_tokens:2048,thinking_config:{thinking_budget:512,include_thoughts:true},top_p:0.8}});});
  assert.equal(await page.locator('#model-max-tokens-input').inputValue(),'2048');
  assert.equal(await page.locator('#model-thinking-budget-input').inputValue(),'512');
  await page.locator('#model-thinking-budget-input').fill('1024');
  assert.deepEqual(JSON.parse(await editor.inputValue()).thinking_config,{thinking_budget:1024,include_thoughts:true});
  // DeepSeek's actual toggle preserves a separate parameter draft for each protocol.
  await page.evaluate(async()=>{await ModelConfigEditor.load('deepseek-chat','deepseek',{request_params:{max_tokens:2048,reasoning_effort:'medium',frequency_penalty:0.4}});});
  await page.evaluate(()=>document.getElementById('deepseek-use-responses-input').click());
  await page.waitForFunction(()=>!document.getElementById('deepseek-use-responses-input').disabled);
  assert.equal(await page.locator('#model-max-tokens-label').innerText(),'Max Output Tokens');
  assert(!('frequency_penalty' in JSON.parse(await editor.inputValue())));
  assert(await page.locator('#deepseek-enable-search-input').isEnabled());
  assert.match(await page.locator('#deepseek-search-label').innerText(), /官方/);
  await page.evaluate(()=>{const input=document.getElementById('deepseek-enable-search-input'); input.checked=true; input.dispatchEvent(new Event('change'));});
  assert(await page.locator('#deepseek-search-group').evaluate(el=>el.classList.contains('hidden')));
  await page.locator('#model-thinking-enabled-input').uncheck();
  assert.equal(JSON.parse(await editor.inputValue()).reasoning.effort, 'none');
  await page.locator('#model-thinking-enabled-input').check();
  await page.locator('#model-thinking-level-select').selectOption('max',{force:true});
  assert.equal(JSON.parse(await editor.inputValue()).reasoning.effort, 'max');
  await editor.fill(JSON.stringify({max_output_tokens:3072,reasoning:{effort:'low',summary:'auto'},text:{verbosity:'low'}}));
  await page.evaluate(()=>document.getElementById('deepseek-use-responses-input').click());
  await page.waitForFunction(()=>!document.getElementById('deepseek-use-responses-input').disabled);
  assert.deepEqual(JSON.parse(await editor.inputValue()),{max_tokens:2048,reasoning_effort:'medium',frequency_penalty:0.4});
  assert(await page.locator('#deepseek-enable-search-input').isEnabled());
  await page.evaluate(()=>document.getElementById('deepseek-use-responses-input').click());
  await page.waitForFunction(()=>!document.getElementById('deepseek-use-responses-input').disabled);
  assert.deepEqual(JSON.parse(await editor.inputValue()),{max_output_tokens:3072,reasoning:{effort:'low',summary:'auto'},text:{verbosity:'low'}});
  await page.evaluate(async()=>{window.deepseekDraft=await ModelConfigEditor.prepareSave(); window.deepseekConfig={}; PlatformSettings.saveAll(window.deepseekConfig); ModelConfigEditor.reset(); PlatformSettings.loadAll(window.deepseekConfig); await ModelConfigEditor.load('deepseek-chat','deepseek',window.deepseekDraft);});
  assert.equal(await page.evaluate(()=>window.deepseekConfig.deepseek_use_responses),true);
  assert.equal(JSON.parse(await editor.inputValue()).max_output_tokens,3072);
  await editor.fill('{broken');
  await page.evaluate(()=>document.getElementById('deepseek-use-responses-input').click());
  await page.waitForFunction(()=>!document.getElementById('deepseek-use-responses-input').disabled);
  assert(await page.locator('#deepseek-use-responses-input').isChecked());
  await page.locator('#restore-model-json-btn').click();
  await page.evaluate(()=>document.getElementById('deepseek-use-responses-input').click());
  await page.waitForFunction(()=>!document.getElementById('deepseek-use-responses-input').disabled);
  // Responses uses a different token key and nested reasoning, while retaining the custom provider ID.
  await page.evaluate(async()=>{await ModelConfigEditor.load('gpt-5','custom:responses-qa',{request_params:{max_tokens:2048,reasoning_effort:'medium'}});});
  assert.equal(await page.locator('#model-max-tokens-label').innerText(),'Max Output Tokens');
  assert.equal(await page.locator('#model-max-tokens-input').inputValue(),'2048');
  assert.equal(await page.locator('#model-thinking-level-select').inputValue(),'medium');
  assert(await page.locator('#model-thinking-enabled-input').isChecked());
  assert.equal(await page.locator('.custom-param-row').count(),0);
  await page.locator('#model-max-tokens-input').fill('3072');
  assert.equal(JSON.parse(await editor.inputValue()).max_output_tokens,3072);
  assert(!('max_tokens' in JSON.parse(await editor.inputValue())));
  await editor.fill(JSON.stringify({max_output_tokens:3072,reasoning:{effort:'high',summary:'auto'},text:{verbosity:'low'}}));
  await page.locator('#model-thinking-level-select').selectOption('low',{force:true});
  assert.deepEqual(JSON.parse(await editor.inputValue()).reasoning,{effort:'low',summary:'auto'});
  const responseDraft = await page.evaluate(()=>ModelConfigEditor.prepareSave());
  assert.equal(responseDraft.request_platform,'custom:responses-qa');
  assert.equal(responseDraft.max_tokens,3072);
  assert.equal(responseDraft.thinking_level,'low');
  assert.deepEqual(responseDraft.request_params.text,{verbosity:'low'});
  await page.locator('#model-thinking-enabled-input').uncheck();
  assert(!('reasoning' in JSON.parse(await editor.inputValue())));
  await page.evaluate(()=>{document.getElementById('cp-provider-adapter-input').value='responses'; updateCustomProviderAdapterUI();});
  assert(!(await page.locator('#cp-file-upload-options').evaluate(el=>el.classList.contains('hidden'))));
  assert(!(await page.locator('#cp-file-upload-purpose-input').evaluate(el=>el.classList.contains('hidden'))));
  assert.match(await page.locator('#cp-provider-adapter-help').textContent(),/Responses/);
  await page.evaluate(async()=>{ModelConfigEditor.reset(); const first=ModelConfigEditor.load('model-one','claude',{}); const second=ModelConfigEditor.load('model-two','deepseek',{}); await Promise.all([first,second]);});
  assert(await page.locator('#add-custom-param-btn').isEnabled());
  // A validation response for an old draft must not overwrite more recent edits.
  await page.evaluate(()=>{window.realPreview=apiBridge.preview_model_request; apiBridge.preview_model_request=data=>new Promise(resolve=>{window.resolvePreview=()=>resolve({params:data.model_config.request_params});}); window.pendingDraft=ModelConfigEditor.prepareSave();});
  await page.waitForFunction(()=>!!window.resolvePreview);
  await editor.fill('{"temperature":0.456}');
  assert.equal(await page.evaluate(async()=>{window.resolvePreview(); const result=await window.pendingDraft; apiBridge.preview_model_request=window.realPreview; return result;}),null);
  assert.equal(JSON.parse(await editor.inputValue()).temperature,0.456);
  // Native search cards match call IDs even when calls overlap, and survive history reload.
  const nativeUI = await page.evaluate(async()=>{
   config.active_platform='deepseek'; config.deepseek_use_responses=true; config.deepseek_enable_web_search=true;
   updateSearchBtnUI();
   messageList.innerHTML=''; appendMessage('assistant','', '',true);
   await window.onStreamMessage('search_start',{id:'ws_1',query:'first'});
   await window.onStreamMessage('search_start',{id:'ws_2',query:'second'});
   const searches=[{id:'ws_1',query:'first',engine:'deepseek_native',results:[]},{id:'ws_2',query:'second',engine:'deepseek_native',results:[]}];
   for(const search of searches) await window.onStreamMessage('search_done',search);
   const live=Array.from(messageList.querySelectorAll('.search-card')).map(card=>card.textContent);
   const content=[{type:'text',text:'answer',_responses:{searches}}];
   const tools=extractToolCallsFromMsg({role:'assistant',content});
   messageList.innerHTML=''; appendMessage('assistant',content,'',false,0,tools);
   return {live,history:messageList.textContent,title:webSearchBtn.title,count:tools.length};
  });
  assert.equal(nativeUI.live.length,2); assert(nativeUI.live[0].includes('first')); assert(nativeUI.live[1].includes('second'));
  assert(nativeUI.live.every(text=>text.includes('已完成')&&!text.includes('未找到')));
  assert.equal(nativeUI.count,2); assert(nativeUI.history.includes('DeepSeek 已完成')); assert(!nativeUI.history.includes('未找到'));
  assert(nativeUI.title.includes('DeepSeek 官方搜索'));
  assert.deepEqual(errors,[]);
  console.log('Browser QA passed: dropdown regressions, JSON/form synchronization, precision, nested fields, deletion, save/reopen, invalid drafts, provider schemas and stale-response protection.');
 } catch(e) { console.log(await page.locator("#model-request-json-error").innerText(),await page.locator("#custom-params-error").innerText(),await page.locator("#model-request-json").inputValue()); console.log(errors); throw e; } finally { await browser.close(); }
})().catch(e=>{console.error(e);process.exitCode=1;});
